### ISSUE TITLE
License of these files

### ISSUE THREAD

**Issue by AaronDewes** [Jerome-Maurin/vmdb2-wrapper#2]
Thanks for you work on this tool.
Can you please add a license to these files? I built a custom tool which generates vmdb2 config files and it'd be great if I could add some of your presets to it (with credit of course). https://github.com/AaronDewes/vmdb-config

**Comment by Jerome-Maurin** [comment]
Hi,

Thanks, sure thing.

I haven't been able to work much on it lately.

Some images might not be working correctly.

If you find something to fix don't hesitate do do a pull request.

Le dim. 27 juin 2021 à 16:54, Aaron Dewes ***@***.***> a
écrit :

**Comment by Jerome-Maurin** [comment]
Done

**Comment by AaronDewes** [comment]
Thanks a lot!
